apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
  annotations:
    cert-manager.io/inject-ca-from: vault/vault-agent-injector-webhook
webhooks:
  - name: vault.hashicorp.com
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: 30
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - vault
            - kube-system
    clientConfig:
      service:
        name: vault-agent-injector
        namespace: vault
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "*"
